package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/term"
)

func runSetup(args []string, log *slog.Logger) error {
	fmt.Println()
	fmt.Println("┌──────────────────────────────────────────────────────┐")
	fmt.Println("│  ForgeGuardian Setup                                 │")
	fmt.Println("│                                                      │")
	fmt.Println("│  Configure dashboard credentials and API settings.   │")
	fmt.Println("│  Writes to .env in the current directory.            │")
	fmt.Println("└──────────────────────────────────────────────────────┘")
	fmt.Println()

	reader := bufio.NewReader(os.Stdin)

	email := setupPrompt(reader, "Admin email", os.Getenv("FG_ADMIN_EMAIL"))
	if email == "" {
		return fmt.Errorf("email is required")
	}

	fmt.Print("  Admin password: ")
	passBytes, err := term.ReadPassword(int(os.Stdin.Fd()))
	fmt.Println()
	if err != nil {
		return fmt.Errorf("could not read password: %w", err)
	}
	password := strings.TrimSpace(string(passBytes))
	if password == "" {
		return fmt.Errorf("password is required")
	}
	if len(password) < 8 {
		return fmt.Errorf("password must be at least 8 characters")
	}

	secret := os.Getenv("FG_SESSION_SECRET")
	if secret == "" {
		b := make([]byte, 32)
		if _, err := rand.Read(b); err != nil {
			return fmt.Errorf("generate session secret: %w", err)
		}
		secret = hex.EncodeToString(b)
	}

	anthropicKey := setupPrompt(reader, "Anthropic API key (for AI features, optional)", os.Getenv("ANTHROPIC_API_KEY"))

	envPath := ".env"
	if len(args) > 0 && args[0] != "" {
		envPath = args[0]
	}

	existing := make(map[string]string)
	if data, err := os.ReadFile(envPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			if k, v, ok := strings.Cut(line, "="); ok {
				existing[k] = v
			}
		}
	}

	existing["FG_ADMIN_EMAIL"] = email
	existing["FG_ADMIN_PASSWORD"] = password
	existing["FG_SESSION_SECRET"] = secret
	if anthropicKey != "" {
		existing["ANTHROPIC_API_KEY"] = anthropicKey
	}

	defaults := map[string]string{
		"POSTGRES_PASSWORD": "devpassword",
	}
	for k, v := range defaults {
		if _, ok := existing[k]; !ok {
			existing[k] = v
		}
	}

	var out strings.Builder
	out.WriteString("# ForgeGuardian environment — generated by fgctl setup\n")
	out.WriteString("# Never commit this file.\n\n")

	out.WriteString("# Dashboard authentication\n")
	out.WriteString(fmt.Sprintf("FG_ADMIN_EMAIL=%s\n", existing["FG_ADMIN_EMAIL"]))
	out.WriteString(fmt.Sprintf("FG_ADMIN_PASSWORD=%s\n", existing["FG_ADMIN_PASSWORD"]))
	out.WriteString(fmt.Sprintf("FG_SESSION_SECRET=%s\n", existing["FG_SESSION_SECRET"]))
	out.WriteString("\n")

	if v, ok := existing["ANTHROPIC_API_KEY"]; ok && v != "" {
		out.WriteString("# AI features (advisory, patch, triage)\n")
		out.WriteString(fmt.Sprintf("ANTHROPIC_API_KEY=%s\n", v))
		out.WriteString("\n")
	}

	out.WriteString("# Docker-compose defaults\n")
	out.WriteString(fmt.Sprintf("POSTGRES_PASSWORD=%s\n", existing["POSTGRES_PASSWORD"]))

	for k, v := range existing {
		switch k {
		case "FG_ADMIN_EMAIL", "FG_ADMIN_PASSWORD", "FG_SESSION_SECRET",
			"ANTHROPIC_API_KEY", "POSTGRES_PASSWORD":
			continue
		}
		out.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	absPath, _ := filepath.Abs(envPath)
	if err := os.WriteFile(envPath, []byte(out.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", envPath, err)
	}

	fmt.Println()
	fmt.Println("  ✓  Configuration saved to", absPath)
	fmt.Println()
	fmt.Println("  Next steps:")
	fmt.Println("    docker compose up -d          # start full stack")
	fmt.Println("    open http://localhost:3000     # open dashboard")
	fmt.Println()
	fmt.Println("  Or run the API directly:")
	fmt.Println("    source .env && go run ./internal/api/        # Linux/macOS")
	fmt.Println("    Get-Content .env | ForEach-Object {          # PowerShell")
	fmt.Println("      if ($_ -match '^([^#][^=]+)=(.*)$') {")
	fmt.Println("        [Environment]::SetEnvironmentVariable($matches[1], $matches[2])")
	fmt.Println("      }")
	fmt.Println("    }; go run ./internal/api/")
	fmt.Println()

	return nil
}

func setupPrompt(reader *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		masked := defaultVal
		if len(masked) > 6 {
			masked = masked[:3] + "***" + masked[len(masked)-3:]
		}
		fmt.Printf("  %s [%s]: ", label, masked)
	} else {
		fmt.Printf("  %s: ", label)
	}
	answer, _ := reader.ReadString('\n')
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return defaultVal
	}
	return answer
}
