apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets-template.yaml
  - api-deployment.yaml
  - dashboard-deployment.yaml
  - intel-agent-cronjob.yaml
  - ingress.yaml
