// Code generated by sqlc. DO NOT EDIT.

package dbsqlc

import "context"

// Querier is the interface implemented by *Queries.
type Querier interface {
	// packages
	UpsertPackage(ctx context.Context, ecosystem, name string) (Package, error)
	GetPackage(ctx context.Context, ecosystem, name string) (PackageWithVersionCount, error)
	ListPackages(ctx context.Context, ecosystem string, limit, offset int32) ([]PackageWithVersionCount, error)
	CountPackages(ctx context.Context, ecosystem string) (int64, error)

	// package versions
	UpsertPackageVersion(ctx context.Context, arg UpsertPackageVersionParams) (PackageVersion, error)
	ListVersions(ctx context.Context, ecosystem, name string) ([]PackageVersion, error)
	GetPackageVersion(ctx context.Context, ecosystem, name, version string) (PackageVersion, error)

	// scan results
	UpsertScanResult(ctx context.Context, arg UpsertScanResultParams) (ScanResult, error)
	GetScanResult(ctx context.Context, ecosystem, name, version string) (ScanResult, error)
	ListRecentScans(ctx context.Context, limit int32) ([]RecentScanRow, error)
	DashboardStats(ctx context.Context) (DashboardStatsRow, error)
	DashboardTimeline(ctx context.Context, days int32) ([]DashboardTimelineRow, error)

	// attestations
	InsertAttestation(ctx context.Context, arg InsertAttestationParams) (Attestation, error)
	GetAttestationBySHA256(ctx context.Context, sha256 string) (AttestationWithPackage, error)
}
