apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: forgeguardian-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: forgeguardian-dashboard
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: ghcr.io/forgeguardian/api
    newTag: "${IMAGE_TAG}"
  - name: ghcr.io/forgeguardian/dashboard
    newTag: "${IMAGE_TAG}"
  - name: ghcr.io/forgeguardian/intel-agent
    newTag: "${IMAGE_TAG}"
